version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ti100600@
      POSTGRES_DB: attdb
    ports:
      - "5432:5432"
    networks:
      - container_network

  app:
    build: .
    ports:
      - "8080:8080"
    image: nguyentien0620/dataservice.web-arm:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=attdb;Username=postgres;Password=Ti100600@
    depends_on:
      - db
    networks:
      - container_network
    platform: linux/arm64/v8
  service:
    build: 
      dockerfile: Dockerfile.service
    image: nguyentien0620/dataservice-arm:latest

    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=attdb;Username=postgres;Password=Ti100600@
    depends_on:
      - db
    networks:
      - container_network
    platform: linux/arm64/v8

networks:
  container_network:
    driver: bridge
