version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ti100600@
      POSTGRES_DB: attdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  # .NET Web App Service
  webapp:
    # image: your-webapp-image  # Replace with your web app Docker image
    build: 
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=attdb;Username=postgres;Password=Ti100600@
      - RabbitMQ__HostName=localhost
    ports:
      - "8080:8080"  # Adjust based on your app's port configuration
    networks:
      - mynetwork

  # .NET Worker Service
  worker:
    # image: your-worker-image  # Replace with your worker service Docker image
    build: 
      dockerfile: Dockerfile.service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=attdb;Username=postgres;Password=Ti100600@
      - RabbitMQ__HostName=localhost
    networks:
      - mynetwork

# Define a Docker network
networks:
  mynetwork:
    driver: bridge

# Define named volumes for PostgreSQL data persistence
volumes:
  postgres_data:
